`include "../master/intf/master_if.sv"
`include "../slave/intf/slave_if.sv"

package pkg;
  import uvm_pkg::*;
  `include "uvm_macros.svh"
  `include "defines.sv"

  `include "../master/sequence_items/aw_tx.sv"
  `include "../master/sequence_items/w_tx.sv"
  `include "../master/sequence_items/ar_tx.sv"
  `include "../slave/sequence_items/b_tx.sv"
  `include "../slave/sequence_items/r_tx.sv"

  `include "../memory/mem_model.sv"
  `include "../env/env_cfg.sv"

  `include "../sequencers/aw_sequencer.sv"
  `include "../sequencers/w_sequencer.sv"
  `include "../sequencers/ar_sequencer.sv"
  `include "../sequencers/b_sequencer.sv"
  `include "../sequencers/r_sequencer.sv"
  `include "../sequencers/master_virtual_sequencer.sv"
  `include "../sequencers/slave_virtual_sequencer.sv"

  `include "../master/sequences/aw_master_seq.sv"
  `include "../master/sequences/w_master_seq.sv"
  `include "../master/sequences/ar_master_seq.sv"
  `include "../slave/sequences/b_slave_seq.sv"
  `include "../slave/sequences/r_slave_seq.sv"

  `include "../master/drivers/aw_master_driver.sv"
  `include "../master/drivers/w_master_driver.sv"
  `include "../master/drivers/ar_master_driver.sv"
  `include "../master/drivers/b_master_driver.sv"
  `include "../master/drivers/r_master_driver.sv"
  `include "../slave/drivers/aw_slave_driver.sv"
  `include "../slave/drivers/w_slave_driver.sv"
  `include "../slave/drivers/ar_slave_driver.sv"
  `include "../slave/drivers/b_slave_driver.sv"
  `include "../slave/drivers/r_slave_driver.sv"

  `include "../master/monitors/aw_master_monitor.sv"
  `include "../master/monitors/w_master_monitor.sv"
  `include "../master/monitors/ar_master_monitor.sv"
  `include "../master/monitors/b_master_monitor.sv"
  `include "../master/monitors/r_master_monitor.sv"
  `include "../slave/monitors/aw_slave_monitor.sv"
  `include "../slave/monitors/w_slave_monitor.sv"
  `include "../slave/monitors/ar_slave_monitor.sv"
  `include "../slave/monitors/b_slave_monitor.sv"
  `include "../slave/monitors/r_slave_monitor.sv"

  `include "../master/agents/aw_master_agent.sv"
  `include "../master/agents/w_master_agent.sv"
  `include "../master/agents/ar_master_agent.sv"
  `include "../master/agents/b_master_agent.sv"
  `include "../master/agents/r_master_agent.sv"
  `include "../slave/agents/aw_slave_agent.sv"
  `include "../slave/agents/w_slave_agent.sv"
  `include "../slave/agents/ar_slave_agent.sv"
  `include "../slave/agents/b_slave_agent.sv"
  `include "../slave/agents/r_slave_agent.sv"

  `include "../env/scoreboard.sv"
  `include "../top/master_proto_module.sv"
  `include "../top/slave_proto_module.sv"
  `include "../env/env.sv"
  `include "../vseq/master_vseq.sv"
  `include "../vseq/slave_vseq.sv"
  `include "../test/sanity_test.sv"
endpackage : pkg
